version: '3.8'

services:
  database:
    image: mysql
    container_name: forum_database
    env_file:
      - .env
    ports:
      - "3306:3306"

  admin:
    image: adminer
    container_name: forum_admin
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8080:8080"
